clc;
clear;
a1 = imread('image24.jpg');
subplot(2,5,1);
imshow(a1);
title('Original');
a = rgb2gray(a1);
subplot(2,5,2);
imshow(a);
title('Gray Scale');

G1=bitget(a,1);
G2=bitget(a,2);
G3=bitget(a,3);
G4=bitget(a,4); 
G5=bitget(a,5);
G6=bitget(a,6);
G7=bitget(a,7);
G8=bitget(a,8);

subplot(2,5,3);
imshow(logical(G1));
title('Bit 1');
subplot(2,5,4);
imshow(logical(G2));
title('Bit 2');
subplot(2,5,5);
imshow(logical(G3));
title('Bit 3');
subplot(2,5,6);
imshow(logical(G4));
title('Bit 4');
subplot(2,5,7);
imshow(logical(G5));
title('Bit 5');
subplot(2,5,8);
imshow(logical(G6));
title('Bit 6');
subplot(2,5,9);
imshow(logical(G7));
title('Bit 7');
subplot(2,5,10);
imshow(logical(G8));
title('Bit 8');