	/* HEXA-DECIMAL ADDITION AND MULTIPLICATION */

#include<iostream.h>
#include<conio.h>
void main()
{
 int n1,n2,ans;
 clrscr();
 cout<<"Enter two hexadecimal numbers ";
 cin>>hex>>n1;
 cin>>hex>>n2;
 char op;
 cout<<"Enter operator ";
 cin>>op;
 switch(op)
 {
  case '+':
  ans=n1+n2;
  cout<<"The result is "<<hex<<ans;
  break;
  case '*':
  ans=n1*n2;
  cout<<"The result is "<<hex<<ans;
  break;
  default:
  cout<<"Invalid Operator";
  break;
  }
 getch();
 }

/* OUTPUT - 1
Enter two hexadecimal numbers 16F 4A2
Enter operator +
The result is 611
*/

/* OUTPUT - 2
Enter two hexadecimal numbers 25 3A
Enter operator *
The result is 862
*/

                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                


                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                


